version: '3'
services:
  # DB
  postgres:
    platform: linux/x86_64
    image: 'postgres:15-alpine'
    container_name: postgres
    env_file: ./.env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

  # API
  api:
    depends_on:
      postgres:
        condition: service_healthy
    image: itki-bot-api
    build: itki-bot-api/.
    env_file: ./.env
    container_name: api
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
      - $DEBUG_PORT:$DEBUG_PORT
    environment:
      - spring.datasource.url=jdbc:postgresql://postgres:5432/itki_db
      - spring.datasource.username=$POSTGRES_USER
      - spring.datasource.password=$POSTGRES_PASSWORD
      - spring.jpa.hibernate.ddl-auto=validate
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    healthcheck:
      test: [ "CMD-SHELL", "curl -X GET localhost:8080/success" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # Node RED
  node-red:
    depends_on:
      api:
        condition: service_healthy
    container_name: node-red
    image: node-red
    environment:
      - TZ=Europe/Kiev
    build: node-red/.
    ports:
      - "1880:1880"
    env_file:
      - .env
    volumes:
      - ./node-red/config:/root/.node-red:delegated
      - /root/.node-red/node_modules
